fix: don't crash when rate limiting

diff --git a/tag/action.yml b/tag/action.yml
--- a/tag/action.yml
+++ b/tag/action.yml
@@ -24,7 +24,9 @@ runs:
           @semantic-release/git
     - name: Release
       shell: bash
-      run: npx semantic-release
+      # Note: semantic-release can partially fail, but still tag (that's important)
+      # so make a best effort to continue in case of error
+      run: npx semantic-release || true
     - name: Validate release tag
       shell: bash
       run: >
